version: '3.8'
services:
    main:
        build:
            context: .
            target: tests
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock