version: '3.8'
services:
    main:
        build:
            context: .
            target: development
        ports:
            - '3001:3001'
            - '5858:5858'
        environment:
            - DB_SCHEMA=EventManagementv6Dev
            - DB_HOST=mysql
            - DB_PORT=33060
            - DB_POOL_SIZE=5
            - PORT=3001
            - DRIVE_STORAGE_PATH=/uploads
            - HOST_NAME=localevmplus.org
        volumes:
            - type: bind
              source: /google-keys
              target: /google-keys

            - type: bind
              source: .
              target: /usr/evm-plus

            - uploads:/uploads
        secrets:
            - db_user
            - db_password
            - discord_client_token
            - aws_access_key_id
            - aws_secret_access_key
            - recaptcha_secret

    mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
            - '33060:33060'
        environment:
            - MYSQL_DATABASE=EventManagementv6Dev
            - MYSQL_USER_FILE=/run/secrets/db_user
            - MYSQL_PASSWORD_FILE=/run/secrets/db_password
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - type: bind
              source: ./mysql-init
              target: /docker-entrypoint-initdb.d

            - db-data:/var/lib/mysql
        secrets:
            - db_user
            - db_password

secrets:
    db_user:
        file: ./keys/db_user

    db_password:
        file: ./keys/db_password

    discord_client_token:
        file: ./keys/discord_client_token

    aws_access_key_id:
        file: ./keys/aws_access_key_id

    aws_secret_access_key:
        file: ./keys/aws_secret_access_key

    recaptcha_secret:
        file: ./keys/recaptcha_secret

volumes:
    db-data:
        driver: local

    uploads:
        driver: local