version: '3.8'
services:
    proxy:
        image: nginx
        networks:
            - frontend
        ports:
            - '80:80'
            - '443:443'
        restart: always
        secrets:
            - key_certificate
            - key_private
            - nginx

    main:
        build:
            context: .
            target: website-runner
        networks:
            - frontend
            - backend
        expose:
            - '3001'
        restart: always
        environment:
            - DB_SCHEMA=EventManagementv6
            - DB_HOST=mysql
            - DB_PORT=33060
            - DB_POOL_SIZE=50
            - PORT=3001
            - DRIVE_STORAGE_PATH=/srv/uploads
            - HOST_NAME=evmplus.org
        volumes:
            - type: bind
              source: /google-keys
              target: /google-keys

            - type: bind
              source: /srv/uploads
              target: /srv/uploads
        secrets:
            - db_user
            - db_password
            - discord_client_token
            - aws_access_key_id
            - aws_secret_access_key
            - recaptcha_secret

    mysql:
        image: mysql:8.0
        networks:
            - backend
        expose:
            - '33060'
        restart: always
        volumes:
            - type: bind
              source: /srv/mysql
              target: /var/lib/mysql
              volume:
                nocopy: true

    capwatch_update:
        build:
            context: .
            target: capwatch-import
        networks:
            - backend
        restart: always
        environment:
            - DB_SCHEMA=EventManagementv6
            - DB_HOST=mysql
            - DB_PORT=33060
            - DB_POOL_SIZE=50
        secrets:
            - db_user
            - db_password
            - discord_client_token
            - capwatch_password
            - capwatch_orgid
            - capwatch_capid

networks:
    frontend:
        driver: bridge
        attachable: false

    backend:
        driver: bridge
        attachable: false

secrets:
    db_user:
        file: ./keys/db_user

    db_password:
        file: ./keys/db_password

    discord_client_token:
        file: ./keys/discord_client_token

    aws_access_key_id:
        file: ./keys/aws_access_key_id

    aws_secret_access_key:
        file: ./keys/aws_secret_access_key

    recaptcha_secret:
        file: ./keys/recaptcha_secret

    key_certificate:
        file: ./keys/site.crt

    key_private:
        file: ./keys/site.pem

    capwatch_orgid:
        file: ./keys/capwatch_orgid
    
    capwatch_capid:
        file: ./keys/capwatch_capid

    capwatch_password:
        file: ./keys/capwatch_password