name: Build and Test

on:
    push:
        branches:
            - master
            - development
    pull_request:
        branches:
            - master
            - development

env:
    COMPOSE_DOCKER_CLI_BUILD: 1
    DOCKER_BUILDKIT: 1
    GITHUB_ACTIONS_ENV: 1

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build code
              run: |
                sudo systemctl start mysql.service
                docker-compose -f docker-compose.dev.yml run dev-setup
                yarn run --cwd=packages/client build

            - name: Test code
              run: |
                yarn run --cwd=packages/server-jest-config test
                yarn run --cwd=packages/server-common test
